---
replicaCount: 1

readinessProbe:
  periodSeconds: 20
  InitialDelaySeconds: 10

livenessProbe:
  periodSeconds: 20
  InitialDelaySeconds: 10

image:
  repository: getmeili/meilisearch
  tag: v0.30.0
  pullPolicy: IfNotPresent

environment:
  MEILI_ENV: production
  # For production deployment, the environment MEILI_MASTER_KEY is required.
  # If MEILI_ENV is set to "production" without setting MEILI_MASTER_KEY, this
  # chart will automatically create a secure MEILI_MASTER_KEY and push it as a
  # secret. Otherwise the below value of MEILI_MASTER_KEY will be used instead.
  # MEILI_MASTER_KEY:
auth:
  # Use an existing Kubernetes secret for the MEILI_MASTER_KEY
  existingMasterKeySecret: "moprs"