apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongo
spec:
  members: 1
  type: ReplicaSet
  version: "6.0.4"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: malaury
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: moprs
      roles:
        - name: readWrite
          db: MopRs
      scramCredentialsSecretName: malaury-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
      spec:
        template:
          spec:
            containers:
              - name: mongodb-agent
                readinessProbe:
                  failureThreshold: 50
                  initialDelaySeconds: 30
                resources:
                  requests:
                    cpu: 150m
                    memory: 400M
                  limits:
                    cpu: 500m
                    memory: 500M
              - name: "mongod"
                resources:
                  requests:
                    cpu: 250m
                    memory: 250M
                  limits:
                    cpu: 1000m
                    memory: 1000M
