apiVersion: v1
kind: Service
metadata:
  name: moprs
  labels:
    app: moprs
spec:
  ports:
  - port: 8080
    name: moprs
  clusterIP: None
  selector:
    app: moprs
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: moprs
spec:
  selector:
    matchLabels:
      app: moprs # has to match .spec.template.metadata.labels
  serviceName: "moprs"
  replicas: 3 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: moprs # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: moprs
        image: malauryd/moprs:latest
        ports:
        - containerPort: 8080
          name: moprs
        env:
        - name: MUSIC_PATH
          value: "./Musics"
        - name: ARL
          valueFrom:
            secretKeyRef:
              name: moprs
              key: arl
        - name: MONGO_URL
          value: "mongodb://mongo.default.svc.cluster.local:27017/?appName=MopRs"