const SEARCH_CONTEXT = 'SEARCH_CONTEXT';
const ALBUM_CONTEXT = 'ALBUM_CONTEXT';
const FAV_CONTEXT = 'FAV_CONTEXT';
const HIST_CONTEXT = 'HIST_CONTEXT';
const SELECT_CONTEXT = 'SELECT_CONTEXT'
const TRENDING_CONTEXT = 'TRENDING_CONTEXT'
const PLAYLIST_CONTEXT = 'PLAYLIST_CONTEXT';
const OWN_PLAYLIST_CONTEXT = 'OWN_PLAYLIST_CONTEXT';

export {
	ALBUM_CONTEXT,
	FAV_CONTEXT,
	HIST_CONTEXT,
	PLAYLIST_CONTEXT,
	OWN_PLAYLIST_CONTEXT,
	SEARCH_CONTEXT,
	SELECT_CONTEXT,
	TRENDING_CONTEXT
};
